### ISSUE TITLE
Chart won't display. Please provide chartConfig example in documentation.

### ISSUE THREAD

**Issue by sharden** [uxigene/MMM-Chart#2]
Can you provide a chartConfig example for the configuration option in your documentation? I use the Chartjs.org format for data display but the chart still does not display. Not sure if this is a module issue or a formatting issue on my part.

Attempting a pie chart: http://www.chartjs.org/samples/latest/charts/pie.html

**Comment by sharden** [comment]
Figured it out. If I don't declare width and height it is set to 0px as the default. So the real issue is that the default of 200px does not apply. Thanks for building this module.

**Comment by uxigene** [comment]
Thanks for asking, I'll fix the default value.

**Comment by tjcuddihy** [comment]
Hi @sharden,
I'm running into the same problems. Would you mind pasting in your code? I'd be keen to see a working example.

Or @MarinescuEvghenii do you have a working example that you can update the README with?

**Comment by uxigene** [comment]
Hi @tjcuddihy, I'll fix this issue later. But for now you can set the dimensions in config.


```
{
  module: 'MMM-Chart',
    config: {
      width: 200,
      height: 200
    }
}
```

**Comment by Baa14453** [comment]
I'm getting the same issue, I've tried defining the width and height but no good.
Any ideas? :(

```
    modules: [
        {
            module: 'MMM-Chart',
            config: {
                width: 800,
                height: 800,
                chartConfig: {
                    type: 'bar',
                    data: {
                        labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
                        datasets: [{
                            label: '# of Votes',
                            data: [12, 19, 3, 5, 2, 3],
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 192, 0.2)',
                                'rgba(153, 102, 255, 0.2)',
                                'rgba(255, 159, 64, 0.2)'
                            ],
                            borderColor: [
                                'rgba(255, 99, 132, 1)',
                                'rgba(54, 162, 235, 1)',
                                'rgba(255, 206, 86, 1)',
                                'rgba(75, 192, 192, 1)',
                                'rgba(153, 102, 255, 1)',
                                'rgba(255, 159, 64, 1)'
                            ],
                            borderWidth: 1
                        }]
                    }
                }
            }
        }
    ]
```

**Comment by uxigene** [comment]
@Baa14453 Didn't had any time to check it with your config. Did you tried just with provided example?

```
modules: [
	{
		module: 'MMM-Chart',
		config: {
			width: 200,
                         height: 200
		}
	}
]
```

**Comment by matinlotfali** [comment]
I want to reopen this issue because even the latest example provided by @evghenix doesn't work.

**Comment by mirrormonark** [comment]
> 

this config is working. i would like know how to do a new chart with pie

**Comment by uxigene** [comment]
@mirrormonark To do a pie chat I guess you can use "chartConfig" property. This property is passed directly to ChartJS library. Check it's documentation https://www.chartjs.org/docs/latest/samples/other-charts/pie.html
