### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by kk98kk** [uxigene/MMM-Chart#4]
If I want to do the git clone, I always get the report: 

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by kk98kk** [comment]
Got it.
You have to edit the link: [git clone git@github.com:MarinescuEvghenii/MMM-Chart.git](url)
into [git clone https://github.com/MarinescuEvghenii/MMM-Chart.git](url)

**Comment by uxigene** [comment]
@kk98kk thanks for pointing this. Updated read.me
